
light:
  # Shelly Plus 1 Light
  - platform: mqtt
    schema: template
    name: "Marty Room Main Lights"
    unique_id: shellyplus1-a8032abc5b4c_mqtt
    qos: 1
    state_topic: "shellyplus1-a8032abc5b4c/status/switch:0"
    command_topic: "shellyplus1-a8032abc5b4c/rpc"
    state_template: "{{'on' if value_json.output == true else 'off' }}"
    command_on_template: '{"id":1, "src": "homeassistant/shellies/shellyplus1-a8032abc5b4c", "method": "Switch.Set", "params":{"id":0,"on":true}}'
    command_off_template: '{"id":1, "src": "homeassistant/shellies/shellyplus1-a8032abc5b4c", "method": "Switch.Set", "params":{"id":0,"on":false}}'
  
  # Shelly 2.5 Channel 1 Light
  - platform: mqtt
    unique_id: marty_bathroom_light
    name: "Marty Bathroom Light"
    state_topic: "shellies/shellyswitch25-C45BBE6B443B/relay/0"
    command_topic: "shellies/shellyswitch25-C45BBE6B443B/relay/0/command"
    payload_on: "on"
    payload_off: "off"
    retain: false
    qos: 1

sensor:
  # Shelly 2.5 Channel 1 Light
  - platform: mqtt
    unique_id: sensor_power_consumption_shelly25_0
    name: "Marty Bathroom Shelly 2.5 Power Consumption Relay 0"
    state_topic: "shellies/shellyswitch25-C45BBE6B443B/relay/0/power"
    unit_of_measurement: "W"
  - platform: mqtt
    unique_id: sensor_power_consumption_shelly25_1
    name: "Marty Bathroom Shelly 2.5 Power Consumption Relay 1"
    state_topic: "shellies/shellyswitch25-C45BBE6B443B/relay/1/power"
    unit_of_measurement: "W"
  - platform: mqtt
    unique_id: sensor_temperature_marty_shelly25
    name: "Temperature Shelly 2.5 - Martys Bathroom"
    state_topic: "shellies/shellyswitch25-C45BBE6B443B/temperature"
    unit_of_measurement: "ºC"
